services:
  web:
    build: .
    image: ghcr.io/ispace-top/zhengyuan-website:latest
    container_name: cms-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - EDITOR_USERNAME=editor
      - EDITOR_PASSWORD=editor123
